# FROM python:3.9-slim

# RUN pip install pytest boto3

# CMD [ "tail", "-f", "/dev/null" ]


# FROM python:3.9-slim

# WORKDIR /app

# COPY requirements.txt .

# RUN pip install --no-cache-dir -r requirements.txt

# COPY app.py .

# CMD ["python", "app.py"]

FROM node:18-alpine

WORKDIR /app

COPY package.json ./

RUN npm install --production

COPY index.js ./

EXPOSE 3000

CMD ["npm", "start"]
