# FROM python:3.9-slim

# RUN pip install pytest boto3

# CMD [ "tail", "-f", "/dev/null" ]


# FROM python:3.9-slim

# WORKDIR /app

# COPY requirements.txt .

# RUN pip install --no-cache-dir -r requirements.txt

# COPY app.py .

# CMD ["python", "app.py"]



# FROM node:18-alpine

# WORKDIR /app

# COPY package.json ./

# RUN npm install --production

# COPY index.js ./

# EXPOSE 3000

# CMD ["npm", "start"]


# Build stage
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app

COPY . .
RUN dotnet restore SampleDotNetApp/SampleDotNetApp.csproj
RUN dotnet publish SampleDotNetApp/SampleDotNetApp.csproj -c Release -o /out

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build /out .

EXPOSE 8080
ENTRYPOINT ["dotnet", "SampleDotNetApp.dll"]
